
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("BackgroundProcessing")]
[assembly: AssemblyDescription("KSP Mod/modlibrary for performing processing on vessels in the background")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("JMP")]
[assembly: AssemblyProduct("BackgroundProcessing")]
[assembly: AssemblyCopyright("Copyright © James Picone 2014")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("1bebe396-0cca-4e8d-b40a-88a393832389")]

 [assembly: AssemblyVersion("0.4.5.1")]